export const mockData = {
  summary: {
    activeCases: 24,
    criticalCases: 6,
    evidenceItems: 81,
    activeIocs: 13,
    investigators: 18,
    pendingAnalysis: 12,
  },
  cases: [
    {
      id: 'DF-2026-014',
      title: 'Ransomware Incident',
      severity: 'Critical',
      status: 'Investigating',
      leadAnalyst: 'R. Jenifer',
      evidence: 14,
      lastActivity: '2 hours ago',
    },
    {
      id: 'DF-2026-013',
      title: 'Insider Activity',
      severity: 'High',
      status: 'Evidence Review',
      leadAnalyst: 'M. Osei',
      evidence: 9,
      lastActivity: '4 hours ago',
    },
    {
      id: 'DF-2026-011',
      title: 'Phishing Campaign',
      severity: 'Medium',
      status: 'Analysis',
      leadAnalyst: 'R. Jenifer',
      evidence: 11,
      lastActivity: '1 day ago',
    },
    {
      id: 'DF-2026-010',
      title: 'Credential Stuffing Attack',
      severity: 'High',
      status: 'Contained',
      leadAnalyst: 'N. Patel',
      evidence: 17,
      lastActivity: '2 days ago',
    },
  ],
  evidence: [
    { id: 'EV-0017', name: 'suspicious_archive.zip', type: 'ZIP ARCHIVE', size: '18.4 MB', hash: '7f8a9d...c31e', status: 'UNDER ANALYSIS', custodian: 'M. Osei' },
    { id: 'EV-0012', name: 'endpoint_memory.dmp', type: 'MEMORY DUMP', size: '4.2 GB', hash: '91f3...8c2', status: 'IN TRANSIT', custodian: 'R. Jenifer' },
    { id: 'EV-0031', name: 'identity_log_01.evtx', type: 'LOG FILE', size: '546 KB', hash: 'ab4d...2fe5', status: 'VALIDATED', custodian: 'M. Osei' },
  ],
  iocs: [
    { id: 'IOC-0042', ioc: '91.214.64.82', type: 'IP Address', risk: 'Critical', confidence: 'High', status: 'Confirmed', firstSeen: '2026-10-06', lastSeen: '2026-10-06', caseId: 'DF-2026-014' },
    { id: 'IOC-0043', ioc: 'support-payroll-update[.]com', type: 'Domain', risk: 'High', confidence: 'High', status: 'Confirmed', firstSeen: '2026-10-02', lastSeen: '2026-10-06', caseId: 'DF-2026-011' },
    { id: 'IOC-0044', ioc: '6f1f8a0b...c51a', type: 'File Hash', risk: 'Critical', confidence: 'High', status: 'Investigating', firstSeen: '2026-10-06', lastSeen: '2026-10-06', caseId: 'DF-2026-014' },
  ],
  timeline: [
    { time: '09:41', title: 'Suspicious login detected', type: 'alert', detail: 'Privileged account access attempt flagged by SIEM' },
    { time: '09:47', title: 'Malicious executable identified', type: 'malware', detail: 'Loader staged with suspicious API calls' },
    { time: '09:52', title: 'Incident created', type: 'case', detail: 'Case assigned to lead investigator' },
    { time: '10:03', title: 'Evidence EV-0012 acquired', type: 'evidence', detail: 'Memory dump acquired from compromised endpoint' },
  ],
  auditLogs: [
    { user: 'R. Jenifer', timestamp: '14:32:11', action: 'Evidence Uploaded', object: 'EV-0017', caseId: 'DF-2026-014', ip: '10.5.12.24', result: 'SUCCESS' },
    { user: 'R. Jenifer', timestamp: '14:27:43', action: 'IOC Created', object: 'IOC-0042', caseId: 'DF-2026-014', ip: '10.5.12.24', result: 'SUCCESS' },
    { user: 'Admin', timestamp: '14:21:18', action: 'Analyst Assigned', object: 'DF-2026-014', caseId: 'DF-2026-014', ip: '10.5.9.12', result: 'SUCCESS' },
  ],
  notifications: [
    'New evidence uploaded',
    'Critical IOC detected',
    'Case assigned',
    'Evidence verification completed',
    'Report generated',
  ],
  reports: [
    { id: 'RPT-001', caseId: 'DF-2026-014', title: 'Ransomware forensic report', status: 'Draft' },
    { id: 'RPT-002', caseId: 'DF-2026-011', title: 'Phishing campaign summary', status: 'Ready for Review' },
  ],
};
